# Generated by Django 5.2 on 2025-05-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMCS', '0002_alter_doctor_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
