# Generated by Django 5.2 on 2025-05-29 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMCS', '0003_doctor_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='hospitalid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='OMCS.hospital'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.IntegerField(choices=[(1, 'Cardiologist'), (2, 'Endocrinologist'), (3, 'Neurologist'), (4, 'Psychiatrists'), (5, 'ENT specialist'), (6, 'Gynaecologist'), (7, 'Orthopaedic surgeon'), (8, 'Pulmonologist')]),
        ),
    ]
