# Generated by Django 5.2 on 2025-05-29 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMCS', '0004_appointments_hospitalid_alter_doctor_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='hospitalid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='OMCS.hospital'),
        ),
    ]
